from typing import Dict, Any, List, Tuple, Generator
from langchain_ollama import ChatOllama
from langchain_core.messages import HumanMessage, SystemMessage
from rag.config import load_config
from rag.ingest import get_chroma_collection_and_embeddings
from rag.prompts import GROUNDED_QA_PROMPT

def format_context(retrieved_docs: List[Any]) -> str:
    """Format retrieved documents with source indicators into a single context string."""
    context_blocks = []
    for doc in retrieved_docs:
        # Strip the 'search_document: ' prefix that was added during ingestion before presenting it to the LLM
        raw_content = doc.page_content
        if raw_content.startswith("search_document: "):
            raw_content = raw_content[len("search_document: "):]

        source = doc.metadata.get("source", "unknown")
        context_blocks.append(f"--- START DOCUMENT: {source} ---\n{raw_content}\n--- END DOCUMENT: {source} ---")
    return "\n\n".join(context_blocks)

def query_rag(question: str) -> Tuple[Generator[str, None, None], List[Dict[str, Any]]]:
    """Execute the query pipeline: embed, retrieve, prompt LLM with grounding, and stream response.

    Args:
        question: The user's query string.

    Returns:
        A tuple of:
          - A generator yielding token strings as they are generated by the LLM.
          - A list of retrieved chunk details (text, score, source) for UI display.
    """
    config = load_config()

    # Load collection and embeddings
    vector_store, _ = get_chroma_collection_and_embeddings()

    # nomic-embed-text requirement: prepend 'search_query: ' to questions
    prefixed_query = f"search_query: {question}"

    # Chroma cosine distance: similarity_search_with_score returns raw distance d.
    # Cosine distance d = 1.0 - CosineSimilarity. So CosineSimilarity = 1.0 - d.
    # Scores closer to 0 are more similar.
    retrieved_with_scores = vector_store.similarity_search_with_score(
        prefixed_query,
        k=config.top_k
    )

    # Process retrieved chunks for reporting
    chunks_info = []
    retrieved_docs = []

    for doc, distance in retrieved_with_scores:
        # Convert distance to similarity score
        # Cosine similarity range: -1 to 1. In Chroma distance range: 0 to 2.
        # similarity = 1.0 - distance
        similarity = 1.0 - distance

        raw_content = doc.page_content
        if raw_content.startswith("search_document: "):
            raw_content = raw_content[len("search_document: "):]

        chunks_info.append({
            "content": raw_content,
            "source": doc.metadata.get("source", "unknown"),
            "chunk_index": doc.metadata.get("chunk_index", 0),
            "char_span": doc.metadata.get("char_span", ""),
            "score": round(similarity, 4)
        })
        retrieved_docs.append(doc)

    # Create LLM prompt
    context_str = format_context(retrieved_docs)
    prompt_formatted = GROUNDED_QA_PROMPT.format(context=context_str, question=question)

    # Initialize ChatOllama with streaming config
    # We pass the temperature (0.0 for deterministic grounding) and prompt caching
    chat_model = ChatOllama(
        model=config.llm_model,
        temperature=0.0,
        base_url="http://localhost:11434",
        # Enable prompt caching via model parameters
        num_predict=512,
        num_ctx=2048,
    )

    # Define streaming generator
    def response_stream_generator() -> Generator[str, None, None]:
        try:
            # We call the stream method on LangChain ChatOllama
            for chunk in chat_model.stream(prompt_formatted):
                yield chunk.content
        except Exception as e:
            yield f"\n\n[Error during model response generation: {e}]"

    return response_stream_generator(), chunks_info
